swagger: "2.0"
info:
  title: Neovotech Programming Task
  description: This is the documentation for Roversparket translator task by Neovotech
  version: 1.0
  contact:
    email: nabil.ahmednsu@gmail.com
  license:
    name: Apache 2.0
    url: "http://apache.org/"
  servers:
    -url: "http://localhost:3000/"
    description: This is the local server

schemes: [http, https]

paths:
#Translate text to rovarsparket
  /translate/normal:
    post:
      summary: Translate text to rovarsparket
      description: Translates a given text to rovarsparket string and returns it
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
      - in: body
        name: text
        schema:
          type: object
          properties:
            text:
              type: string
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              success:
                type: boolean
              message:
                type: string
              translation:
                type: string
        400:
          description: Bad Request
          schema:
            $ref: "#/components/schemas/error"
        500:
          description: Internal Server Error
          schema:
            $ref: "#/components/schemas/error"


#Translate roversparket string to text
  /translate/rovarspraket:
      post:
        summary: Translate rovarsparket to normal text
        description: Translates a given rovarsparket string to a normal text and returns it
        produces:
          - application/json
        consumes:
          - application/json
        parameters:
        - in: body
          name: text
          schema:
            type: object
            properties:
              text:
                type: string
        responses:
          200:
            description: Success
            schema:
              type: object
              properties:
                success:
                  type: boolean
                message:
                  type: string
                joke:
                  type: string
                translation:
                  type: string
          400:
            description: Bad Request
            schema:
              $ref: "#/components/schemas/error"
          500:
            description: Internal Server Error
            schema:
              $ref: "#/components/schemas/error"

#Translate roversparket string to text
  /translate/translateJokeOfTheDay:
      post:
        summary: Fetch Joke of the day and translate to rovarsparket and send both text and translation
        description: Translates a given text to rovarsparket string and returns it
        responses:
          200:
            description: Success
            schema:
              type: object
              properties:
                success:
                  type: boolean
                message:
                  type: string
                translation:
                  type: string
          400:
            description: Bad Request
            schema:
              $ref: "#/components/schemas/error"
          500:
            description: Internal Server Error
            schema:
              $ref: "#/components/schemas/error"


components:
  schemas:
    error:
      type: object
      properties:
        success:
          type: boolean
        code:
          type: string
        message:
          type: string

